sudo: required

language: python

services:
  - docker

before_install:
#  - docker build -t gym-gazebo .
  - docker pull erlerobotics/gym-gazebo # to fetch the container
  - docker images

#  - docker run -it erlerobotics/gym-gazebo

  - docker run erlerobotics/gym-gazebo /bin/sh -c "cd gym-gazebo/gym_gazebo/envs/installation; . turtlebot_setup.bash; cd /usr/local/gym/gym-gazebo/examples/scripts_turtlebot/; python maze_turtlebot_lidar_qlearn.py"

  # - cd gym-gazebo/gym_gazebo/envs/installation
  # - . turtlebot_setup.bash
  # - cd /usr/local/gym/gym-gazebo/examples/scripts_turtlebot/
  # - python maze_turtlebot_lidar_qlearn.py

